module.exports.BASE_URL = '/api/'
module.exports.BASE_HOST = 'https://comicvine.gamespot.com'

module.exports.CHANNELS = '/channels'

module.exports.SEARCH = (query) => `/search/?query=${query}`
module.exports.ISSUE = (id) => `/issue/4000-${id}/`
module.exports.VOLUME = (id) => `/volume/4050-${id}/`
module.exports.CHARACTER = '/character'
module.exports.CHARACTERS = '/characters'
module.exports.CHAT = '/chat'
module.exports.CHATS = '/chats'
module.exports.CONCEPT = '/concept'
module.exports.CONCEPTS = '/concepts'
module.exports.EPISODE = '/episode'
module.exports.EPISODES = '/episodes'
// module.exports.ISSUE = '/issue'
module.exports.ISSUES = '/issues'
module.exports.LOCATION = '/location'
module.exports.LOCATIONS = '/locations'
module.exports.MOVIE = '/movie'
module.exports.MOVIES = '/movies'
module.exports.OBJECT = '/object'
module.exports.OBJECTS = '/objects'
module.exports.ORIGIN = '/origin'
module.exports.ORIGINS = '/origins'
module.exports.PERSON = '/person'
module.exports.PEOPLE = '/people'
module.exports.POWER = '/power'
module.exports.POWERS = '/powers'
module.exports.PROMO = '/promo'
module.exports.PROMOS = '/promos'
module.exports.PUBLISHER = '/publisher'
module.exports.PUBLISHERS = '/publishers'
// module.exports.SERIES = '/series'
module.exports.SERIES_LIST = '/series_list'
// module.exports.SEARCH = '/search'
module.exports.STORY_ARC = '/stort_arc'
module.exports.STORY_ARCS = '/story_arcs'
module.exports.TEAM = '/team'
module.exports.TEAMS = '/teams'
module.exports.TYPES = '/types'
module.exports.VIDEO = '/video'
module.exports.VIDEOS = '/videos'
module.exports.VIDEO_TYPE = '/video_type'
module.exports.VIDEO_TYPES = '/video_types'
module.exports.VIDEO_CATEGORY = '/video_category'
module.exports.VIDEO_CATEGORIES = '/video_catergories'
// module.exports.VOLUME = '/volume'
module.exports.VOLUMES = '/volumes'
